# Generated by Django 4.1.3 on 2022-11-16 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='name',
            new_name='email',
        ),
    ]
