# Generated by Django 4.1.3 on 2022-11-16 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_message_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='recipent',
            new_name='recipient',
        ),
    ]
